#!/usr/bin/env bash
set -e

url=$( gpg --decrypt encrypts/justmysocks_suburl.txt.gpg 2> /dev/null )

rm -rf justmysocks-*.yaml
go run ./cmd/justmysocks $url 1> justmysocks-$(date -u +%Y%m%d%H%M%S).yaml
