#!/usr/bin/env bash
set -e

os=$(uname)

if [[ $os == "Darwin" ]]; then
    brew install fish
else
    sudo apt install fish
fi

# set it as default
chsh -s $(which fish)

# install starship
curl -sS https://starship.rs/install.sh | sh

exit 1
