#!/usr/bin/env bash
set -e

url=

os=$(uname)
if [[ $os == "Linux" ]]; then
    url=https://go.dev/dl/go1.24.3.linux-amd64.tar.gz
else
    echo "unknown os: $os"
    exit 1
fi


rm -rf /tmp/go
mkdir /tmp/go
cd /tmp/go
curl -L -o go.tar.gz $url
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go.tar.gz
rm -rf /tmp/go
