#!/usr/bin/env bash
set -e

dir="/tmp/luals"
os=$(uname | tr "[:upper:]" "[:lower:]")
platform=$(uname -m)
if [[ $platform == "x86_64" ]]; then
    platform="x64"
fi
version="3.13.3"
filename="lua-language-server"


rm -rf $dir
mkdir -p $dir
cd $dir
curl -OL "https://github.com/LuaLS/lua-language-server/releases/download/$version/lua-language-server-$version-$os-$platform.tar.gz"
gzip -fd lua-language-server-$version-$os-$platform.tar.gz
tar xvf lua-language-server-$version-$os-$platform.tar
rm -rf lua-language-server-$version-$os-$platform.tar
cp -R $dir $HOME/.local
rm -rf $dir
