#!/usr/bin/env bash
set -e

dir="/tmp/neovim"
os=$(uname | tr "[:upper:]" "[:lower:]")
version=nightly
#v0.10.4

# 1 install neovims
sudo rm -rf $dir

# clone repo
git clone --depth 1 --branch $version https://github.com/neovim/neovim.git $dir
# install deps
if [[ $os == "linux" ]]; then
    sudo apt install ninja-build gettext cmake unzip curl build-essential
elif [[ $os == "darwin" ]]; then
    brew install ninja cmake gettext curl
else
    echo "unknown os: $os"
    exit 1
fi

pushd $dir
# build
make CMAKE_BUILD_TYPE=Release
# install
sudo make install
popd

# 2 install plugin deps
# 2.1 fd
if [[ $os == "linux" ]]; then
    sudo apt install fd-find
    sudo ln -fs $(which fdfind) /usr/local/bin/fd
elif [[ $os == "darwin" ]]; then
    brew install fd
else
    echo "unknown os: $os"
    exit 1
fi
# 2.2 ripgrep
if [[ $os == "linux" ]]; then
    sudo apt install ripgrep
elif [[ $os == "darwin" ]]; then
    brew install ripgrep
else
    echo "unknown os: $os"
    exit 1
fi

# clean up
sudo rm -rf $dir

