#!/usr/bin/env bash

# install zig

os=$(uname | tr "[:upper:]" "[:lower:]")
if [[ $os == "darwin" ]]; then
    os="macos"
fi
machine=$(uname -m)
if [[ $machine == "arm64" ]]; then
    machine="aarch64"
fi
version="0.14.0"
filename="zig-$os-$machine-$version"
zipfile="$filename.tar.xz"
url="https://ziglang.org/download/$version/$zipfile"

rm -rf /tmp/zig
mkdir /tmp/zig
cd /tmp/zig
curl -L -o zig.tar.gz $url
tar xf zig.tar.gz
cp -r $filename/. ~/.local/share/zig
cd - 2> /dev/null
rm -rf /tmp/zig

# install zls
rm -rf /tmp/zls
mkdir /tmp/zls
cd /tmp/zls
curl -L -o zls.tar.gz https://builds.zigtools.org/zls-$os-$machine-$version.tar.xz
tar xf zls.tar.gz
mv zls ~/.local/share/zig
