[general]
import = ['~/.config/alacritty/themes/themes/gruvbox_dark.toml']

[env]
TERM = "xterm-256color"

[window]
padding = { x = 0, y = 0 }
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.85
blur = false
startup_mode = "SimpleFullscreen"

[font]
normal.family = 'JetBrainsMono Nerd Font' # 'MonaspiceNe Nerd Font Propo' 
size = 16
offset.y = 0

[[keyboard.bindings]]
key = "Key1"
mods = "Command"
chars ="\u001b1" # remap Cmd+1 to Ecs+1

[[keyboard.bindings]]
key = "Key2"
mods = "Command"
chars ="\u001b2"

[[keyboard.bindings]]
key = "Key3"
mods = "Command"
chars ="\u001b3"

[[keyboard.bindings]]
key = "Key4"
mods = "Command"
chars ="\u001b4"

[[keyboard.bindings]]
key = "Key5"
mods = "Command"
chars ="\u001b5"
